### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by a330068666** [iwantavnow/Setting.App#1]
appear    WinHttpSendRequest：12007：无法解析服务器的名称或地址

**Comment by iwantavnow** [comment]
Installation is required some Network availability, we are working on an offline installer.

**Comment by iwantavnow** [comment]
Enterprise version is current available.

**Comment by RivenYuKi** [comment]
我也是无法解析服务器的名称或地址

**Comment by mengmeng123qas** [comment]
我也是无法解析

**Comment by qq3565522** [comment]
求你了要不改收费的吧这也装不上啊

**Comment by iwantavnow** [comment]
Now we provide TF distribution!

**Comment by mengmeng123qas** [comment]
666
---原始邮件---
发件人:&quot;Setting.App&quot;<notifications@github.com&gt;
发送时间:2021年1月6日 星期三 下午3:44
收件人:&quot;iwantavnow/Setting.App&quot;<Setting.App@noreply.github.com&gt;
抄送:&quot;mengmeng123qas&quot;<61388846@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;
主题:Re: [iwantavnow/Setting.App] Installation problem (#1)



Now&nbsp;we&nbsp;provide&nbsp;TF&nbsp;distribution!

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;commented.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.
